### ISSUE TITLE
Demo link is not working

### ISSUE THREAD

**Issue by esaesa** [kartik-v/yii2-word-report#1]
## Prerequisites

- [y ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ y] The issue still exists against the latest `master` branch of yii2-word-report.
- [y ] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/word-report) and [demos](http://demos.krajee.com/word-report-demo).
- [y ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Visit demo link from the repository read me

## Expected behavior and actual behavior

When I follow those steps, I see...
![image](https://user-images.githubusercontent.com/5354709/108859993-762d0a80-75f6-11eb-9def-6359b130795f.png)

I was expecting...

#### Browsers

- [y ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [y ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-word-report version:

## Isolating the problem

- [ y] This bug happens [on the demos page](https://demos.krajee.com/word-report-demo)
- [y ] The bug happens consistently across all tested browsers
- [ y] This bug happens when using yii2-word-report without other plugins.

**Comment by kartik-v** [comment]
Hi - this extension is under development - demo page is not yet up. Will update once done.
